apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy: { type: Recreate }
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
        - --source=ingress
        - --domain-filter=marcodoes.tech
        - --provider=cloudflare
        - --cloudflare-proxied
        - --txt-owner-id=k3s-nuc-1
        - --exclude-record-types=A
        - --expose-internal-ipv6
        - --cloudflare-record-comment="provisioned by external-dns"
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: token