apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bandcheck
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/m-gora/bandcheck.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bandcheck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
